# Generated by Django 4.1.5 on 2023-02-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_logitude_userprofile_lognitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lognitude',
            new_name='longitude',
        ),
    ]
